services:
  flask-app:
    container_name: flask-app
    build:
      context: .
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      FLASK_APP: "app.py"       # Set the main Flask app file
      FLASK_ENV: "production"   # Set Flask environment
    volumes:
      - .:/app # Mount the current directory to the container
